[build]
  command = "npm run build"

[build.environment]
  NODE_VERSION = "22"

# Next.js plugin will auto-detect .next output
[[plugins]]
  package = "@netlify/plugin-nextjs"

[[plugins]]
  package = "netlify-plugin-checklinks"

  [plugins.inputs]
    skipPatterns = [
      ".next/pricing"
    ]
